In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])
print(arr1)
print(arr1.shape)

[1 2 3]
(3,)


In [13]:
arr1.reshape(3, 1)
arr1.shape

(3,)

In [20]:
arr2 = np.array([[1, 2, 3], [4, 5,7]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 7]]
(2, 3)


In [23]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
a = np.array([1, 2, 3, 4, 5])
print(np.sqrt(a))
print(np.log(a))
print(np.sin(a))
print(np.exp(a))

[1.         1.41421356 1.73205081 2.         2.23606798]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [42]:
a = np.array([[1, 2,4,5], [3, 4,5,6,] ,[5, 6,7,8]])
print("array :\n", a)

array :
 [[1 2 4 5]
 [3 4 5 6]
 [5 6 7 8]]


In [55]:
a[0][2]


np.int64(4)

In [58]:
a[1: , 2:]

array([[5, 6],
       [7, 8]])

In [62]:
a[0:2,:1]

array([[1],
       [3]])

In [65]:
a[1,1] = 10
a

array([[ 1,  2,  4,  5],
       [ 3, 10,  5,  6],
       [ 5,  6,  7,  8]])

In [72]:
#normalization (std -1 , mean 0)
data = np.random.randn(10)
print("mean :", np.mean(data))
print("std :", np.std(data))
normalizatioon = data - np.mean(data) / np.std(data)
print(normalizatioon)

mean : 0.08676179044513747
std : 0.7726170481734814
[ 0.65277307  0.7830072  -0.12102409  0.16255976 -0.8643653  -0.34446137
  0.19194098 -1.22331503  1.34181638 -0.83427352]


In [74]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
a1>10
a1[a1>5]  ###mandt to write like tghis 

array([ 6,  7,  8,  9, 10])

In [81]:
import pandas as pd

#Series is 1d even dict key will create as index 
data = [1, 2, 3, 4, 5, 6 ]
index = [0, 2, 4, 6, 8, 10]
pd.Series(data, index = index)

0     1
2     2
4     3
6     4
8     5
10    6
dtype: int64

In [121]:
#dataframe is 2d
data = {'Name': ['Tom', 'Nick', 'John'],
        'Age': [20, 21 , 0 ],
        'city' : ['NY', 'LA', 'SF']}

df = pd.DataFrame(data)
print(df)


   Name  Age city
0   Tom   20   NY
1  Nick   21   LA
2  John    0   SF


In [ ]:
a1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(a1)



In [107]:
df.head()

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [109]:
df.iloc[0]

0    1
1    2
2    3
Name: 0, dtype: int64

In [114]:
df.loc[0][1]

np.int64(2)

In [116]:
df.head(2)

0  1  2
0  1  2  3
1  4  5  6

In [124]:
df.head(2).tail(1)

Name  Age city
1  Nick   21   LA

In [127]:
df.iat[2, 2]

'SF'

In [138]:
df['salary'] = [100, 200, 300]
df

Name city  salary
0   Tom   NY     100
1  Nick   LA     200
2  John   SF     300

In [ ]:
df.drop('Age',axis = 1 , inplace = True)   #permanent delete from df 

In [139]:
df['salary']= df['salary'].apply(lambda x: x*2)

In [140]:
df

Name city  salary
0   Tom   NY     200
1  Nick   LA     400
2  John   SF     600

In [ ]:
df = pd.read_csv('/small_movies_Y.csv')
df.head()

0.0  0.0.1  0.0.2  0.0.3  0.0.4  0.0.5  0.0.6  0.0.7  0.0.8  0.0.9  ...  \
0  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3  5.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   0.0.428  0.0.429  0.0.430  0.0.431  0.0.432  0.0.433  0.0.434  0.0.435  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      2.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      1.0      0.0      0.0      4.0   
4      0.0      3.0      0.0      0.0      0.0      0.0      0.0      0.0   

   0.0.436  0.0.437  
0      0.0      0.0  
1      0.0      0.0  
2      0.0      0.0  
3      3.0      3.0  
4      4.5      0.0  

[5 rows x 443 columns]

In [145]:
df.tail()

0.0  0.0.1  0.0.2  0.0.3  0.0.4  0.0.5  0.0.6  0.0.7  0.0.8  0.0.9  ...  \
4772  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4773  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4774  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4775  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4776  0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

      0.0.428  0.0.429  0.0.430  0.0.431  0.0.432  0.0.433  0.0.434  0.0.435  \
4772      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4773      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4774      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4775      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4776      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

      0.0.436  0.0.437  
4772      0.0      0.0  
4773      0.0      0.0  
4774      0.0      0.0  
4775      0.0      0.0  
4776      0.0      0.0  

[5 rows x 443 columns]

In [146]:
df.describe()

0.0        0.0.1        0.0.2        0.0.3        0.0.4  \
count  4777.000000  4777.000000  4777.000000  4777.000000  4777.000000   
mean      0.004815     0.021562     0.000314     0.023446     0.059661   
std       0.149601     0.297526     0.012527     0.296325     0.457694   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       5.000000     5.000000     0.500000     5.000000     5.000000   

             0.0.5        0.0.6        0.0.7        0.0.8        0.0.9  ...  \
count  4777.000000  4777.000000  4777.000000  4777.000000  4777.000000  ...   
mean      0.010676     0.087921     0.006908     0.014235     0.059766  ...   
std       0.211903     0.566564     0.180887     0.236456     0.464887  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
max       5.000000     5.000000     5.000000     5.000000     5.000000  ...   

           0.0.428      0.0.429      0.0.430      0.0.431      0.0.432  \
count  4777.000000  4777.000000  4777.000000  4777.000000  4777.000000   
mean      0.016119     0.484195     0.111995     0.061964     0.047101   
std       0.272158     1.066768     0.608614     0.522256     0.413447   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       0.000000     0.000000     0.000000     0.000000     0.000000   
max       5.000000     5.000000     5.000000     5.000000     5.000000   

           0.0.433      0.0.434      0.0.435      0.0.436      0.0.437  
count  4777.000000  4777.000000  4777.000000  4777.000000  4777.000000  
mean      0.070232     0.238853     0.006908     0.216245     0.755390  
std       0.475683     0.916701     0.152294     0.891416     1.504107  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       5.000000     5.000000     5.000000     5.000000     5.000000  

[8 rows x 443 columns]

In [147]:
df.isnull()

0.0  0.0.1  0.0.2  0.0.3  0.0.4  0.0.5  0.0.6  0.0.7  0.0.8  0.0.9  \
0     False  False  False  False  False  False  False  False  False  False   
1     False  False  False  False  False  False  False  False  False  False   
2     False  False  False  False  False  False  False  False  False  False   
3     False  False  False  False  False  False  False  False  False  False   
4     False  False  False  False  False  False  False  False  False  False   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
4772  False  False  False  False  False  False  False  False  False  False   
4773  False  False  False  False  False  False  False  False  False  False   
4774  False  False  False  False  False  False  False  False  False  False   
4775  False  False  False  False  False  False  False  False  False  False   
4776  False  False  False  False  False  False  False  False  False  False   

      ...  0.0.428  0.0.429  0.0.430  0.0.431  0.0.432  0.0.433  0.0.434  \
0     ...    False    False    False    False    False    False    False   
1     ...    False    False    False    False    False    False    False   
2     ...    False    False    False    False    False    False    False   
3     ...    False    False    False    False    False    False    False   
4     ...    False    False    False    False    False    False    False   
...   ...      ...      ...      ...      ...      ...      ...      ...   
4772  ...    False    False    False    False    False    False    False   
4773  ...    False    False    False    False    False    False    False   
4774  ...    False    False    False    False    False    False    False   
4775  ...    False    False    False    False    False    False    False   
4776  ...    False    False    False    False    False    False    False   

      0.0.435  0.0.436  0.0.437  
0       False    False    False  
1       False    False    False  
2       False    False    False  
3       False    False    False  
4       False    False    False  
...       ...      ...      ...  
4772    False    False    False  
4773    False    False    False  
4774    False    False    False  
4775    False    False    False  
4776    False    False    False  

[4777 rows x 443 columns]

In [151]:
df.isnull().any()

0.0        False
0.0.1      False
0.0.2      False
0.0.3      False
0.0.4      False
           ...  
0.0.433    False
0.0.434    False
0.0.435    False
0.0.436    False
0.0.437    False
Length: 443, dtype: bool

In [152]:
df.isnull().sum()

0.0        0
0.0.1      0
0.0.2      0
0.0.3      0
0.0.4      0
          ..
0.0.433    0
0.0.434    0
0.0.435    0
0.0.436    0
0.0.437    0
Length: 443, dtype: int64

In [ ]:
df['Age'] = df['budget'].fillna(df['budget'].mean ()).astype(int)
df['Age'] = df['Age'].apply(lambda x: x*2)

In [ ]:
grouped_mean = df.groupby('Product')['salary'].mean()  #mean of salary by product
multiple_grouping = df.groupby(['Product ' ,'Age'])['salary'].mode()  #mode of salary by product and age
grouped_mean = df.groupby('Product')['salary'].agg(['mean', 'median', 'std'])  #mean, median, std of salary by product

In [168]:
#merging and joing df 
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2',  'A3'],
                    'B': ['B0', 'B1', 'B2','B3'],
                    'C': ['C0', 'C1', 'C2', 'C3']})

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6',  'A7'],
                    'B': ['B4', 'B5', 'B6','B7'],
                    'D': ['D4', 'D5', 'D6', 'D7']})

pd.merge(df1, df2, on = 'B', how = 'outer')  
#outer join , left join, right join, inner join,lefe outer join, right outer join

A_x   B    C  A_y    D
0   A0  B0   C0  NaN  NaN
1   A1  B1   C1  NaN  NaN
2   A2  B2   C2  NaN  NaN
3   A3  B3   C3  NaN  NaN
4  NaN  B4  NaN   A4   D4
5  NaN  B5  NaN   A5   D5
6  NaN  B6  NaN   A6   D6
7  NaN  B7  NaN   A7   D7

In [166]:
df1 , df2

(    A   B   C
 0  A0  B0  C0
 1  A1  B1  C1
 2  A2  B2  C2
 3  A3  B3  C3,
     A   B   D
 0  A4  B4  D4
 1  A5  B5  D5
 2  A6  B6  D6
 3  A7  B7  D7)

In [171]:
pip install lxml

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 11.6 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [174]:
##reaading data from weebsite 
url = 'https://www.fdic.gov/bank-failures/failed-bank-list'
df = pd.read_html(url)

In [175]:
df[0]

Bank Name               City          State  \
0     The First National Bank of Lindsay            Lindsay       Oklahoma   
1  Republic First Bank dba Republic Bank       Philadelphia   Pennsylvania   
2                          Citizens Bank           Sac City           Iowa   
3               Heartland Tri-State Bank            Elkhart         Kansas   
4                    First Republic Bank      San Francisco     California   
5                         Signature Bank           New York       New York   
6                    Silicon Valley Bank        Santa Clara     California   
7                      Almena State Bank             Almena         Kansas   
8             First City Bank of Florida  Fort Walton Beach        Florida   
9                   The First State Bank      Barboursville  West Virginia   

    Cert                 Aquiring Institution      Closing Date  \
0   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024   
1  27332    Fulton Bank, National Association    April 26, 2024   
2   8758            Iowa Trust & Savings Bank  November 3, 2023   
3  25851               Dream First Bank, N.A.     July 28, 2023   
4  59017            JPMorgan Chase Bank, N.A.       May 1, 2023   
5  57053                  Flagstar Bank, N.A.    March 12, 2023   
6  24735  First Citizens Bank & Trust Company    March 10, 2023   
7  15426                          Equity Bank  October 23, 2020   
8  16748            United Fidelity Bank, fsb  October 16, 2020   
9  14361                       MVB Bank, Inc.     April 3, 2020   

   Fund  Sort ascending  
0                 10547  
1                 10546  
2                 10545  
3                 10544  
4                 10543  
5                 10540  
6                 10539  
7                 10538  
8                 10537  
9                 10536

In [181]:
df1 = pd.read_html(url , match = 'City')[0]

In [180]:
df1[0]

Bank Name               City          State  \
0     The First National Bank of Lindsay            Lindsay       Oklahoma   
1  Republic First Bank dba Republic Bank       Philadelphia   Pennsylvania   
2                          Citizens Bank           Sac City           Iowa   
3               Heartland Tri-State Bank            Elkhart         Kansas   
4                    First Republic Bank      San Francisco     California   
5                         Signature Bank           New York       New York   
6                    Silicon Valley Bank        Santa Clara     California   
7                      Almena State Bank             Almena         Kansas   
8             First City Bank of Florida  Fort Walton Beach        Florida   
9                   The First State Bank      Barboursville  West Virginia   

    Cert                 Aquiring Institution      Closing Date  \
0   4134   First Bank & Trust Co., Duncan, OK  October 18, 2024   
1  27332    Fulton Bank, National Association    April 26, 2024   
2   8758            Iowa Trust & Savings Bank  November 3, 2023   
3  25851               Dream First Bank, N.A.     July 28, 2023   
4  59017            JPMorgan Chase Bank, N.A.       May 1, 2023   
5  57053                  Flagstar Bank, N.A.    March 12, 2023   
6  24735  First Citizens Bank & Trust Company    March 10, 2023   
7  15426                          Equity Bank  October 23, 2020   
8  16748            United Fidelity Bank, fsb  October 16, 2020   
9  14361                       MVB Bank, Inc.     April 3, 2020   

   Fund  Sort ascending  
0                 10547  
1                 10546  
2                 10545  
3                 10544  
4                 10543  
5                 10540  
6                 10539  
7                 10538  
8                 10537  
9                 10536